# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<-'SCRIPT'
apt-get update
apt-get install -y python3
apt-get install -y python3-pip
apt-get install -y libpq-dev
pip3 install django
pip3 install psycopg2-binary


# apt-get install -y libreadline-dev 
# apt-get install -y zlib1g-dev
# curl -k https://ftp.postgresql.org/pub/source/v8.4.1/postgresql-8.4.1.tar.gz --output /home/vagrant/postgresql-8.4.1.tar.gz
# cd /home/vagrant/
# tar -xvf /home/vagrant/postgresql-8.4.1.tar.gz
# export CFLAGS=-fno-aggressive-loop-optimizations
# /home/vagrant/postgresql-8.4.1/configure
# make install
# adduser --disabled-password --gecos "" postgres
# mkdir -p /usr/local/pgsql/data
# chown postgres /usr/local/pgsql/data
# sudo -u postgres /usr/local/pgsql/bin/initdb -D /usr/local/pgsql/data
SCRIPT

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-18.04"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: $script
  config.vm.provision "file", source: "/Users/f1restarter/Documents/skillfactory/vagrant/6/emptyfile.py", destination: "~/"
  #config.vm.provision "shell", inline: <<-SHELL
  # sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  # wget --no-check-certificate  https://www.postgresql.org/media/keys/ACCC4CF8.asc -P /home/vagrant/
  # apt-key add //home/vagrant/ACCC4CF8.asc
 
  #   apt-get install -y apache2
  # SHELL
end
